### ISSUE TITLE
Question regarding mi-svm

### ISSUE THREAD

**Issue by sedghi** [AMLab-Amsterdam/AttentionDeepMIL#13]
Hi, I know this is not an issue with the repository, but i'm curious about the framework you used for mi-svm and how MNIST data was feeded into mi-svm? did you flatten the images?

Thanks

**Comment by max-ilse** [comment]
Hi, if you sent me an email I will send you the code.

**Comment by sedghi** [comment]
Thanks I'll send an email soon
