### ISSUE TITLE
Keras_Implementation_Colon_Cancer

### ISSUE THREAD

**Issue by utayao** [AMLab-Amsterdam/AttentionDeepMIL#4]
Hi, This is a very interesting work and I implement the Colon cancer part in your paper using Keras. It would be very nice if you can check if my [implementation](https://github.com/utayao/Atten_Deep_MIL) is correct. Thanks.

**Comment by jmtomczak** [comment]
Hi!
Thanks for letting us know! I looked into your implementation and I don't see any mistake. Well done!
