### ISSUE TITLE
the problem of mean bag length

### ISSUE THREAD

**Issue by connorchen** [AMLab-Amsterdam/AttentionDeepMIL#5]
hi,
you said 'Mean bag length parameter shouldn't be much larger than 10', however the paper Attention-based Deep Multiple Instance Learning says that 'In the experiments we use different numbers of the mean
bag size, namely, 10 , 50 and 100'. How to explain this contradiction， in my experiments no matter what the variance is,  the proportion will be unbalanced as long as the mean bag length more than 10.

**Comment by max-ilse** [comment]
Hi,

For simplicity the data loader in this repo is not the one that was used in the original experiments.

**Comment by rjbruin** [comment]
I'm also concerned about this. I've reproduced your code and I am able to reproduce your results for mean bag size 10, but for higher bag sizes I'm seeing nearly exclusively positive ground truth bags (as to be expected when sampling for `n > 10` instances and a chance of `1/10` to draw a positive sample) leading to the model overfitting on solely positive predictions.

Can you share the original data loader? I will send you an email as well, but it seems to me it would also be a valuable addition to this repository.

**Comment by max-ilse** [comment]
Hey everybody,

I just added the data loader. It is not as clean as the rest of the code but is doing the job.

Best,
Max
