### ISSUE TITLE
What's the bag length in Colon data?

### ISSUE THREAD

**Issue by s4384596** [AMLab-Amsterdam/AttentionDeepMIL#6]
Hi,

I just tried to implement the model on Colon data, the average bag length is just about 100, so the result is pretty bad. Can I know roughly how many patches did you generate for each image in your experiment?

Regards,
Mark

**Comment by max-ilse** [comment]
Hi Mark,

I don't fully understand your question, since the number of images in a bag are predetermined by the dataset itself. Feel free to drop me a mail so we can discuss this issue in more detail: m.ilse@uva.nl

**Comment by s4384596** [comment]
I already figured out the reason for the bad result, and it was not caused by the number of pathces, but the image normalization process. Anyway, thanks for your response.
