### ISSUE TITLE
Steps to modify the code for the Breast and colon dataset

### ISSUE THREAD

**Issue by hawkeyedesi** [AMLab-Amsterdam/AttentionDeepMIL#9]
I wanted to replicate the experiment in the paper for the Breast and the Colon dataset. I wanted to know if this rough roadmap of code modification is correct or not: 

1. Create a custom data loader by modifying the existing MnistBags. Also, create a custom loader for actually reading in the Histopath images. 
2. Change the number of patches per bag as described in the paper. 
3. The network remains the same LeNet (as mentioned in the ReadME)
4. The Hyperparameters remain the same I presume. 

Any guidance on creating the modifications especially the data loader will be appreciated. 
Thanks

**Comment by max-ilse** [comment]
Hey there,
I have to see if I find time to clean up the original code and uploaded in the next weeks.

Until then you can have a look at this implementation: https://github.com/utayao/Atten_Deep_MIL

**Comment by hawkeyedesi** [comment]
Thanks for pointing it out. I look forward to seeing your original code soon.
